### ISSUE TITLE
The attack success rate for CXR and Derm is not as expected

### ISSUE THREAD

**Issue by ChisamXz** [sgfin/adversarial-medicine#2]
When I tested the PGD attacks on the three dataset. The attack result for the DR is exactly the same as in the paper. However, the CXR and DERM do not have a correct result. The CXR model even can not achieve the correct prediction on clean images. My results for the three datasets are attached:

![result](https://user-images.githubusercontent.com/45636391/55652891-da544480-57ba-11e9-9861-48e94850d379.png)

I'm almost sure that I followed the correct procedures and had modified the paths in the "craft_attacks.py" correctly. If it's convenient, would it be possible to check if the models are correct?

**Comment by sgfin** [comment]
Thanks so much -- again -- for running the code.  Glad the DR worked, hopefully that means it was just the other models got uploaded incorrectly.  (I had been moving all these models around last minute on the dropbox before making public, so I'm sure I just did something stupid when uploading.  Should have re-downloaded and re-run to be safe. Sorry.)

**Comment by sgfin** [comment]
Hi there,

I re-uploaded the files to dropbox, downloaded separately onto my server, and reran the code.  The results reproduced what was in the paper, so I am guessing that the problem was a data transfer issue.   
 Hopefully that is resolved now.  See below for the code I ran and screencap of the output.

I took this chance to slightly refactor the script, and also to produce a yaml for the PGD environment, since I had to recreate this anyway to run my tests.  I hope this is helpful.

Best,
Sam

### CXR
`python craft_attacks.py --pathModel models_to_share/cxr/wb_model.h5 --pathBBWeights models_to_share/cxr/bb_weights.hdf5 --pathDataX numpy_to_share/cxr/val_test_x_preprocess.npy --pathDataY numpy_to_share/cxr/val_test_y.npy --dontSaveResults --gpu1`

![image](https://user-images.githubusercontent.com/2760120/55665653-b708b400-5811-11e9-97e4-9f8caf94f221.png)

### Derm

`python craft_attacks.py --pathModel models_to_share/derm/wb_model.h5 --pathBBWeights models_to_share/derm/bb_weights.hdf5 --pathDataX numpy_to_share/derm/val_test_x_preprocess.npy --pathDataY numpy_to_share/derm/val_test_y.npy --dontSaveResults --gpu1`

![image](https://user-images.githubusercontent.com/2760120/55665456-f92ff680-580d-11e9-8e0b-4fcbb7f909bf.png)
